-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivity$g
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Args
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Error
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningEphemeralKeyProvider
# Keep Stripe classes
-keep class com.stripe.** { *; }

# Keep kotlinx.parcelize runtime interfaces and annotation used by libraries (e.g., Stripe)
-keep class kotlinx.parcelize.Parceler { *; }
-keep class kotlinx.parcelize.Parceler$* { *; }
-keep class kotlinx.parcelize.Parcelize { *; }

# Keep any classes annotated with @Parcelize
-keep @kotlinx.parcelize.Parcelize class * { *; }

# Keep Parcelable creators
-keepclassmembers class * implements android.os.Parcelable {
	public static final android.os.Parcelable$Creator CREATOR;
}

# Keep Stripe Android SDK entry points and models that may be referenced reflectively
-keep class com.stripe.android.** { *; }
-dontwarn com.stripe.android.**

# Keep any synthetic/default impl classes generated by Kotlin that might be referenced
-keep class kotlin.Metadata { *; }
-keep class kotlin.jvm.internal.* { *; }